server:
  host: "aneworders.com"
  port: "443"

database:
  host: "mysql"
  port: "3306"
  user: "root"
  password: "123456"
  dbname: "gongchang"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0

jwt:
  secret: "your-secret-key"
  expire: 24 