server:
  host: "0.0.0.0"
  port: "8080"
  trusted_proxies:
    - "127.0.0.1"
    - "::1"
    - "0.0.0.0"
    - "aneworders.com"

database:
  host: "gongchang-mysql"
  port: "3306"
  user: "gongchang"
  password: "gongchang"
  dbname: "gongchang"

redis:
  host: "redis"
  port: "6379"
  password: ""
  db: 0

jwt:
  secret: "your-secret-key"
  expiration: 24 # hours

upload:
  max_size: 10 # MB
  allowed_types: ["image/jpeg", "image/png", "application/pdf"]
  path: "./uploads" 