server:
  host: "0.0.0.0"
  port: "8080"
  trusted_proxies: ["127.0.0.1", "::1"]

database:
  host: "mysql"
  port: "3306"
  user: "root"
  password: "root"
  dbname: "gongchang"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0

jwt:
  secret: "your-secret-key"
  expire: 24 