server:
  port: "8080"

database:
  host: "localhost"
  port: "3306"
  user: "root"
  password: "password"
  dbname: "sewingmast"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0

jwt:
  secret: "your-secret-key"
  expire: 24 