version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8088:8088"
      - "443:443"  # HTTPS 端口
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=sewingmast
      - DB_PASSWORD=sewingmast123
      - DB_NAME=sewingmast
      - JWT_SECRET=your-jwt-secret
      - SSL_CERT_FILE=/ssl/cert.pem
      - SSL_KEY_FILE=/ssl/key.pem
    depends_on:
      mysql:
        condition: service_healthy
    restart: always

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sewingmast
      - MYSQL_USER=sewingmast
      - MYSQL_PASSWORD=sewingmast123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  mysql_data: 