version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "443:443"
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=gongchang
      - JWT_SECRET=your-secret-key
      - SERVER_HOST=aneworders.com
      - SERVER_PORT=443
    depends_on:
      - mysql
    networks:
      - gongchang_network

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=gongchang
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - gongchang_network

networks:
  gongchang_network:
    driver: bridge

volumes:
  mysql_data: 