# 注意：重启容器时不要使用 docker-compose down -v，这会删除所有数据卷
# 正确的重启命令是：docker-compose down && docker-compose up -d

version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: gongchang_backend
    restart: always
    ports:
      - "8008:8008"
    environment:
      - DB_HOST=192.168.0.10
      - DB_PORT=3306
      - DB_USER=gongchang
      - DB_PASSWORD=gongchang
      - DB_NAME=gongchang
      - JWT_SECRET=your_jwt_secret_key
    networks:
      - gongchang_network

networks:
  gongchang_network:
    driver: bridge 
