version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: gongchang-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gongchang
      MYSQL_USER: gongchang
      MYSQL_PASSWORD: gongchang
    ports:
      - "3306:3306"
    volumes:
      - gongchang_mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    user: "1000:1000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gongchang-backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=gongchang
      - DB_PASSWORD=gongchang
      - DB_NAME=gongchang
    depends_on:
      - mysql
    restart: always

volumes:
  gongchang_mysql_data:
    driver: local 