CREATE TABLE IF NOT EXISTS `orders` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `deleted_at` datetime(3) DEFAULT NULL,
  `title` longtext NOT NULL,
  `description` longtext,
  `fabric` longtext,
  `quantity` bigint DEFAULT NULL,
  `factory_id` varchar(191) DEFAULT NULL,
  `status` varchar(191) DEFAULT 'draft',
  `designer_id` longtext,
  `customer_id` longtext,
  `unit_price` double DEFAULT NULL,
  `total_price` double DEFAULT NULL,
  `payment_status` longtext,
  `shipping_address` longtext,
  `order_type` longtext,
  `fabrics` longtext,
  `delivery_date` datetime(3) DEFAULT NULL,
  `order_date` datetime(3) DEFAULT NULL,
  `special_requirements` longtext,
  `attachments` json DEFAULT NULL,
  `models` json DEFAULT NULL,
  `images` json DEFAULT NULL,
  `videos` json DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_orders_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci; 