CREATE TABLE IF NOT EXISTS `orders` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `deleted_at` datetime(3) DEFAULT NULL,
  `title` longtext NOT NULL,
  `description` longtext,
  `fabric` longtext,
  `quantity` bigint DEFAULT NULL,
  `factory_id` varchar(191) DEFAULT NULL,
  `status` varchar(191) DEFAULT 'draft',
  `designer_id` longtext,
  `customer_id` longtext,
  `unit_price` double DEFAULT NULL,
  `total_price` double DEFAULT NULL,
  `payment_status` longtext,
  `shipping_address` longtext,
  `order_type` longtext,
  `fabrics` longtext,
  `delivery_date` datetime(3) DEFAULT NULL,
  `order_date` datetime(3) DEFAULT NULL,
  `special_requirements` longtext,
  `attachments` json DEFAULT NULL,
  `models` json DEFAULT NULL,
  `images` json DEFAULT NULL,
  `videos` json DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_orders_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- 接单表
CREATE TABLE IF NOT EXISTS `jiedan` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `order_id` bigint unsigned NOT NULL COMMENT '订单ID',
  `factory_id` varchar(191) NOT NULL COMMENT '工厂ID',
  `status` varchar(50) NOT NULL DEFAULT 'pending' COMMENT '状态：pending-待处理, accepted-已同意, rejected-已拒绝',
  `price` decimal(10,2) DEFAULT NULL COMMENT '接单价格',
  `jiedan_time` datetime(3) DEFAULT NULL COMMENT '接单时间',
  `agree_time` datetime(3) DEFAULT NULL COMMENT '同意时间',
  `agree_user_id` varchar(191) DEFAULT NULL COMMENT '同意的用户ID',
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `deleted_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_jiedan_order_id` (`order_id`),
  KEY `idx_jiedan_factory_id` (`factory_id`),
  KEY `idx_jiedan_status` (`status`),
  KEY `idx_jiedan_deleted_at` (`deleted_at`),
  CONSTRAINT `fk_jiedan_order_id` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE CASCADE,
  UNIQUE KEY `uk_order_factory` (`order_id`, `factory_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='接单表';

-- 订单进度表
CREATE TABLE IF NOT EXISTS `order_progress` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `order_id` bigint unsigned NOT NULL COMMENT '订单ID',
  `factory_id` varchar(191) NOT NULL COMMENT '工厂ID',
  `type` varchar(50) NOT NULL COMMENT '进度类型：design-设计阶段, material-材料准备, production-生产阶段, quality-质检阶段, packaging-包装阶段, shipping-发货阶段, custom-自定义阶段',
  `status` varchar(50) NOT NULL DEFAULT 'not_started' COMMENT '进度状态：not_started-未开始, in_progress-进行中, completed-已完成, delayed-延期, on_hold-暂停',
  `description` text COMMENT '进度描述',
  `start_time` datetime(3) DEFAULT NULL COMMENT '开始时间',
  `completed_time` datetime(3) DEFAULT NULL COMMENT '完成时间',
  `images` text COMMENT '图片URL数组(JSON格式)',
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `deleted_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_order_progress_order_id` (`order_id`),
  KEY `idx_order_progress_factory_id` (`factory_id`),
  KEY `idx_order_progress_status` (`status`),
  KEY `idx_order_progress_deleted_at` (`deleted_at`),
  CONSTRAINT `fk_order_progress_order_id` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='订单进度表';

-- 工厂职工管理表
CREATE TABLE IF NOT EXISTS `factory_employees` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL COMMENT '职工姓名',
  `position` varchar(100) NOT NULL COMMENT '职位',
  `grade` varchar(50) DEFAULT NULL COMMENT '年级/级别',
  `work_years` int DEFAULT 0 COMMENT '工龄(年)',
  `factory_id` varchar(191) NOT NULL COMMENT '工厂ID',
  `hire_date` date NOT NULL COMMENT '入职时间',
  `phone` varchar(20) DEFAULT NULL COMMENT '联系电话',
  `email` varchar(100) DEFAULT NULL COMMENT '邮箱',
  `department` varchar(100) DEFAULT NULL COMMENT '部门',
  `salary` decimal(10,2) DEFAULT NULL COMMENT '薪资',
  `status` varchar(20) DEFAULT 'active' COMMENT '状态：active-在职，inactive-离职',
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `deleted_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_factory_employees_factory_id` (`factory_id`),
  KEY `idx_factory_employees_status` (`status`),
  KEY `idx_factory_employees_deleted_at` (`deleted_at`),
  CONSTRAINT `fk_factory_employees_factory_id` FOREIGN KEY (`factory_id`) REFERENCES `factory_profiles` (`user_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='工厂职工管理表'; 